QBShared = QBShared or {}
QBShared.Vehicles = QBShared.Vehicles or {}

local Vehicles = {
    --- Cycles (1)
    {['model'] = 'bmx',           ['name'] = 'BMX',                           ['brand'] = 'Bike',            ['price'] = 160,     ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'cruiser',       ['name'] = 'Cruiser',                       ['brand'] = 'Bike',            ['price'] = 510,     ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'fixter',        ['name'] = 'Fixter',                        ['brand'] = 'Bike',            ['price'] = 225,     ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'scorcher',      ['name'] = 'Scorcher',                      ['brand'] = 'Bike',            ['price'] = 280,     ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'tribike',       ['name'] = 'Whippet Race Bike',             ['brand'] = 'Bike',            ['price'] = 500,     ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'tribike2',      ['name'] = 'Endurex Race Bike',             ['brand'] = 'Bike',            ['price'] = 700,     ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'tribike3',      ['name'] = 'Tri-Cycles Race Bike',          ['brand'] = 'Bike',            ['price'] = 520,     ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'inductor',      ['name'] = 'Inductor',                      ['brand'] = 'Coil',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'inductor2',     ['name'] = 'Junk Energy Inductor',          ['brand'] = 'Coil',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = '22Surron',     ['name'] = 'Surron',          ['brand'] = 'Electric',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'africat',     ['name'] = 'Africa Twin',          ['brand'] = 'Honda',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'cb650r',     ['name'] = 'CB650R',          ['brand'] = 'Honda',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'd99',     ['name'] = 'D99',          ['brand'] = 'Ducati',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'diavel',     ['name'] = 'Diavel Carbon',          ['brand'] = 'Ducati',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'dmons',     ['name'] = 'Monster',          ['brand'] = 'Ducati',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'gsxr',     ['name'] = 'GSXR',          ['brand'] = 'Suzuki',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'sxf450sm',     ['name'] = 'SXF450',          ['brand'] = 'KTM',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'v4sf',     ['name'] = 'Streetfighter',          ['brand'] = 'Ducati',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'r1',     ['name'] = 'R1',          ['brand'] = 'Kawasaki',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'zx10r22',     ['name'] = 'Ninja',          ['brand'] = 'Kawasaki',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'katana',     ['name'] = 'Katana',          ['brand'] = 'Suzuki',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'sanchez2',     ['name'] = 'Sanchez',          ['brand'] = 'Maibatsu',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    {['model'] = 'sanchez',     ['name'] = 'Sanchez',          ['brand'] = 'Maibatsu',            ['price'] = 5000,    ['categoryLabel'] = 'Cycles',          ['shop'] = 'none'},
    --- Boats (2)
    {['model'] = 'dinghy4',       ['name'] = 'Weaponized Dinghy',             ['brand'] = 'Nagasaki',        ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'avisa',         ['name'] = 'Avisa',                         ['brand'] = 'Kraken Subs',     ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'patrolboat',    ['name'] = 'Kurtz 31 Patrol Boat',          ['brand'] = 'Unknown',         ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'longfin',       ['name'] = 'Longfin',                       ['brand'] = 'Shitzu',          ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'tug',           ['name'] = 'Tug',                           ['brand'] = 'Buckingham',      ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'toro',          ['name'] = 'Toro',                          ['brand'] = 'Lampadati',       ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'toro2',         ['name'] = 'Toro Yacht',                    ['brand'] = 'Lampadati',       ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'submersible2',  ['name'] = 'Kraken',                        ['brand'] = 'Kraken Subs',     ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'speeder',       ['name'] = 'Speeder',                       ['brand'] = 'Pegassi',         ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'speeder2',      ['name'] = 'Speeder Yacht',                 ['brand'] = 'Pegassi',         ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'tropic',        ['name'] = 'Tropic',                        ['brand'] = 'Shitzu',          ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'tropic2',       ['name'] = 'Tropic Yacht',                  ['brand'] = 'Shitzu',          ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'suntrap',       ['name'] = 'Suntrap',                       ['brand'] = 'Shitzu',          ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'submersible',   ['name'] = 'Submersible',                   ['brand'] = 'Kraken Subs',     ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'squalo',        ['name'] = 'Squalo',                        ['brand'] = 'Shitzu',          ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'seashark',      ['name'] = 'Seashark',                      ['brand'] = 'Speedophile',     ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'seashark3',     ['name'] = 'Seashark Yacht',                ['brand'] = 'Speedophile',     ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'marquis',       ['name'] = 'Marquis',                       ['brand'] = 'Dinka',           ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'jetmax',        ['name'] = 'Jetmax',                        ['brand'] = 'Shitzu',          ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'dinghy',        ['name'] = 'Dinghy 2-Seater',               ['brand'] = 'Nagasaki',        ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'dinghy2',       ['name'] = 'Dinghy 4-Seater',               ['brand'] = 'Nagasaki',        ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'dinghy3',       ['name'] = 'Dinghy (Heist)',                ['brand'] = 'Nagasaki',        ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    {['model'] = 'dinghy4',       ['name'] = 'Dinghy Yacht',                  ['brand'] = 'Nagasaki',        ['price'] = 40000,   ['categoryLabel'] = 'none',           ['shop'] = 'none'},
    --- Helicopters (3)
    {['model'] = 'conada2',       ['name'] = 'Weaponized Conada',             ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'conada',        ['name'] = 'Conada',                        ['brand'] = 'Buckingham',      ['price'] = 115000,  ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'seasparrow2',   ['name'] = 'Sparrow',                       ['brand'] = 'Unknown',         ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'annihilator2',  ['name'] = 'Annihilator Stealth',           ['brand'] = 'Western Company', ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'seasparrow',    ['name'] = 'Sea Sparrow',                   ['brand'] = 'Unknown',         ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'akula',         ['name'] = 'Akula',                         ['brand'] = 'Unknown',         ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'hunter',        ['name'] = 'FH-1 Hunter',                   ['brand'] = 'Unknown',         ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'havok',         ['name'] = 'Havok',                         ['brand'] = 'Nagasaki',        ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'volatus',       ['name'] = 'Volatus',                       ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'supervolito2',  ['name'] = 'SuperVolito Carbon',            ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'supervolito',   ['name'] = 'SuperVolito',                   ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'swift2',        ['name'] = 'Swift Deluxe',                  ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'valkyrie',      ['name'] = 'Valkyrie',                      ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'savage',        ['name'] = 'Savage',                        ['brand'] = 'Unknown',         ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'swift',         ['name'] = 'Swift',                         ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'annihilator',   ['name'] = 'Annihilator',                   ['brand'] = 'Western Company', ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'cargobob2',     ['name'] = 'Cargobob Jetsam',               ['brand'] = 'Western Company', ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'skylift',       ['name'] = 'Skylift',                       ['brand'] = 'HVY',             ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'maverick',      ['name'] = 'Maverick',                      ['brand'] = 'Buckingham',      ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'frogger',       ['name'] = 'Frogger',                       ['brand'] = 'Maibatsu',        ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'frogger2',      ['name'] = 'Frogger',                       ['brand'] = 'Maibatsu',        ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'cargobob',      ['name'] = 'Cargobob',                      ['brand'] = 'Western Company', ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'cargobob3',     ['name'] = 'Cargobob',                      ['brand'] = 'Western Company', ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'seasparrow3',   ['name'] = 'Sparrow (Prop)',                ['brand'] = 'Unknown',         ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'buzzard',       ['name'] = 'Buzzard Attack Chopper',        ['brand'] = 'Nagasaki',        ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    {['model'] = 'buzzard2',      ['name'] = 'Buzzard',                       ['brand'] = 'Nagasaki',        ['price'] = 52000,   ['categoryLabel'] = 'Helicopters',     ['shop'] = 'none'},
    --- Planes (4)
    {['model'] = 'streamer216',   ['name'] = 'Streamer216',                   ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'raiju',         ['name'] = 'F-160 Raiju',                   ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'alkonost',      ['name'] = 'RO-86 Alkonost',                ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'strikeforce',   ['name'] = 'B-11 Strikeforce',              ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'blimp3',        ['name'] = 'Blimp',                         ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'avenger',       ['name'] = 'Avenger',                       ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'avenger2',      ['name'] = 'Avenger',                       ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'volatol',       ['name'] = 'Volatol',                       ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'nokota',        ['name'] = 'P-45 Nokota',                   ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'seabreeze',     ['name'] = 'Seabreeze',                     ['brand'] = 'Western Company', ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'pyro',          ['name'] = 'Pyro',                          ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'mogul',         ['name'] = 'Mogul',                         ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'howard',        ['name'] = 'Howard NX-25',                  ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'bombushka',     ['name'] = 'RM-10 Bombushka',               ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'molotok',       ['name'] = 'V-65 Molotok',                  ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'microlight',    ['name'] = 'Ultralight',                    ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'tula',          ['name'] = 'Tula',                          ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'rogue',         ['name'] = 'Rogue',                         ['brand'] = 'Western Company', ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'starling',      ['name'] = 'LF-22 Starling',                ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'alphaz1',       ['name'] = 'Alpha-Z1',                      ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'nimbus',        ['name'] = 'Nimbus',                        ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'luxor2',        ['name'] = 'Luxor Deluxe',                  ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'velum2',        ['name'] = 'Velum 5-seater',                ['brand'] = 'JoBuilt',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'hydra',         ['name'] = 'Hydra',                         ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'blimp2',        ['name'] = 'Xero Blimp',                    ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'dodo',          ['name'] = 'Dodo',                          ['brand'] = 'Mammoth',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'miljet',        ['name'] = 'Miljet',                        ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'besra',         ['name'] = 'Besra',                         ['brand'] = 'Western Company', ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'vestra',        ['name'] = 'Vestra',                        ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'cargoplane',    ['name'] = 'Cargo Plane',                   ['brand'] = 'JoBuilt',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'velum',         ['name'] = 'Velum',                         ['brand'] = 'JoBuilt',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'titan',         ['name'] = 'Titan',                         ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'shamal',        ['name'] = 'Shamal',                        ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'lazer',         ['name'] = 'P-996 Lazer',                   ['brand'] = 'JoBuilt',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'mammatus',      ['name'] = 'Mammatus',                      ['brand'] = 'JoBuilt',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'stunt',         ['name'] = 'Mallard',                       ['brand'] = 'Western Company', ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'luxor',         ['name'] = 'Luxor',                         ['brand'] = 'Buckingham',      ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'jet',           ['name'] = 'Jet',                           ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'duster',        ['name'] = 'Duster',                        ['brand'] = 'Western Company', ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'cuban800',      ['name'] = 'Cuban 800',                     ['brand'] = 'Western Company', ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    {['model'] = 'blimp',         ['name'] = 'Atomic Blimp',                  ['brand'] = 'Unknown',         ['price'] = 45000,   ['categoryLabel'] = 'Planes',          ['shop'] = 'none'},
    --- Police (5)
    {['model'] = 'a4-unmarked',          ['name'] = 'POLICE AUDI A4',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'ERT8',          ['name'] = 'BMW 2 Series Marked',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'ERT9',          ['name'] = 'Peugeot 308 Marked',                   ['brand'] = 'Peugeot',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'ERT23',          ['name'] = 'FORD Transit Van',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'jagf',          ['name'] = 'Jaguar F Pace',                   ['brand'] = 'Jaguar',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'jagxf',          ['name'] = 'Jaguar XFR',                   ['brand'] = 'Jaguar',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'm5f90',          ['name'] = 'BMW M5 F90',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 's4m',          ['name'] = 'POLICE AUDI A4',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'ERT20',          ['name'] = 'Sprinter Van Marked',                   ['brand'] = 'Mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'pol_bmw1',          ['name'] = 'BMW 3 Series Unmarked',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'pol_subaru',          ['name'] = 'Subaru Marked',                   ['brand'] = 'SUBARU',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'polarvgud',          ['name'] = 'BMW 330i',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'polastra',          ['name'] = 'Vauxhall Astra Marked',                   ['brand'] = 'Vauxhall',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'poldirtb',          ['name'] = 'POLICE AUDI A4',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'polgolf',          ['name'] = 'Golf Unmarked',                   ['brand'] = 'Volkswagen',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'policeb',          ['name'] = 'R900RTP Bike',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'polrange',          ['name'] = 'Range Rover SVR Marked',                   ['brand'] = 'Range Rover',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'unmarkeda6',          ['name'] = 'Audi A6 Unmarked',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'unmarkeda45',          ['name'] = 'Benz A45 Unmarked',                   ['brand'] = 'Mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'pursport',          ['name'] = 'Bugatti Chiron',                   ['brand'] = 'Bugatti',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'nm_ctsv',          ['name'] = 'Cadillac CTS-V',                   ['brand'] = 'Cadillac',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'psenna',          ['name'] = 'Mclaren Senna',                   ['brand'] = 'Mclaren',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'x5f15',          ['name'] = 'BMW X5F15',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'x6mpd',          ['name'] = 'BMW X6 Unmarked',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'x3m3tour22',          ['name'] = 'BMW M3 Touring Unmarked',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'rs318',          ['name'] = 'AUDI RS3 Sportback Unmarked',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'rs322sedancarbontels',          ['name'] = 'AUDI RS3 Sedan Unmarked',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'r35kream',          ['name'] = 'Nissan GT-R Unmarked',                   ['brand'] = 'Nissan',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'pctp',          ['name'] = 'Porsche Cayenne Unmarked',                   ['brand'] = 'Porsche',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'fordrsc',          ['name'] = 'Ford Focus RS Unmarked',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'm140icun',          ['name'] = 'BMW M140 I',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'rj71ygc',          ['name'] = 'BMW X5 Unmarked',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'km72mte',          ['name'] = 'Range Rover Unmarked',                   ['brand'] = 'Range Rover',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'VRESG05',          ['name'] = 'BMW X5 GO5 Marked',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'SegG3001',          ['name'] = 'BMW 3 Series',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'FX22FMC',          ['name'] = 'Volvo XC 90',                   ['brand'] = 'Volvo',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'bmwm2els',          ['name'] = 'BMW M2 Marked',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'npas',          ['name'] = 'npas',                   ['brand'] = 'EUROCOPTER',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = 'm2cs20',          ['name'] = 'm2cs20',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    {['model'] = '4x4range',          ['name'] = '4x4range',                   ['brand'] = '4x4 Range Rover',           ['price'] = 100000,  ['categoryLabel'] = 'Police',       ['shop'] = 'none'},
    --- NHS (6)
    {['model'] = 'x5nhs',          ['name'] = 'NHS X5',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'octavia2010',          ['name'] = 'NHS Octavia Estate',                   ['brand'] = 'Skoda',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'x5aa',          ['name'] = 'NHS X5',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'HEMS1',          ['name'] = 'NHS HEMS HELI',                   ['brand'] = 'EUROCOPTER',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'Nhsbike',          ['name'] = 'NHS R1200RT',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'nhsc8',          ['name'] = 'NHS X5 RS6',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'nhsfiat',          ['name'] = 'NHS FIAT VAN',                   ['brand'] = 'FIAT',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'nhsmerc',          ['name'] = 'NHS MERC',                   ['brand'] = 'MERCEDES',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'nhsq8',          ['name'] = 'NHS RSQ8',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    {['model'] = 'nhsrs7',          ['name'] = 'NHS RS7',                   ['brand'] = 'AUDI',           ['price'] = 100000,  ['categoryLabel'] = 'NHS',       ['shop'] = 'none'},
    --- AA (7)
    {['model'] = 'aaconnect',          ['name'] = 'AA FORD CONNECT',                   ['brand'] = 'FORD',           ['price'] = 100000,  ['categoryLabel'] = 'AA',       ['shop'] = 'none'},
    {['model'] = 'aatransit',          ['name'] = 'AA FORD TRANSIT',                   ['brand'] = 'FORD',           ['price'] = 100000,  ['categoryLabel'] = 'AA',       ['shop'] = 'none'},
    {['model'] = 'aaflatbed',          ['name'] = 'AA FLATBED',                   ['brand'] = 'FORD',           ['price'] = 100000,  ['categoryLabel'] = 'AA',       ['shop'] = 'none'},
    {['model'] = 'AAamarok',          ['name'] = 'AA AMAROK',                   ['brand'] = 'VOLKSWAGEN',           ['price'] = 100000,  ['categoryLabel'] = 'AA',       ['shop'] = 'none'},
    {['model'] = 'aafocus',          ['name'] = 'AA FORD FOCUS',                   ['brand'] = 'FORD',           ['price'] = 100000,  ['categoryLabel'] = 'AA',       ['shop'] = 'none'},
    --- ANIMATED (8)
    {['model'] = 'ocnetrongt',          ['name'] = 'E-Tron',                   ['brand'] = 'audi',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = 'm4comp',          ['name'] = 'M4 Comp',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = 'zl12017',          ['name'] = 'Camaro zl1',                   ['brand'] = 'Chevrolet',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = 'gcmlamboultimae',          ['name'] = 'Aventador',                   ['brand'] = 'lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = '18performante',          ['name'] = 'Huracan Tecnica',                   ['brand'] = 'lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = 'lbdy01',          ['name'] = 'veneno',                   ['brand'] = 'lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = 'mcgt20',          ['name'] = 'GT',                   ['brand'] = 'Mclaren',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = 'e63amg',          ['name'] = 'E63',                   ['brand'] = 'AMG',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    {['model'] = 'skyline',          ['name'] = 'Skyline',                   ['brand'] = 'Nissan',           ['price'] = 100000,  ['categoryLabel'] = 'ANIMATED',       ['shop'] = 'none'},
    --- RMOD (9)
    {['model'] = 'rmodatlantic',          ['name'] = 'Rmod Atlantic',                   ['brand'] = 'BUGATTI',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodbacalar',          ['name'] = 'Rmod Atlantic',                   ['brand'] = 'Rmod mulliner',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodbentleygt',          ['name'] = 'Rmod GT',                   ['brand'] = 'Rmod bentley',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodbiposto',          ['name'] = 'rmodbiposto',                   ['brand'] = 'rmodbiposto',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodc63amg',          ['name'] = 'Rmod C63 AMG',                   ['brand'] = 'Rmod mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmode63s',          ['name'] = 'Rmod E63S Brabus',                   ['brand'] = 'Rmod mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodessenza',          ['name'] = 'Rmod Essenza',                   ['brand'] = 'Rmod Lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodf12tdf',          ['name'] = 'Rmod F12',                   ['brand'] = 'Rmod Ferrari',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodf40',          ['name'] = 'Rmod F40',                   ['brand'] = 'Rmod Ferrari',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodgtr50',          ['name'] = 'Rmod GT-R 50',                   ['brand'] = 'Rmod Nissan',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodi8ks',          ['name'] = 'Rmod I8',                   ['brand'] = 'Rmod BMW',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodjeep',          ['name'] = 'Rmod Grand Cherokee Trackhawk',                   ['brand'] = 'Rmod Jeep',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodjesko',          ['name'] = 'Rmod Regera',                   ['brand'] = 'Rmod Keonigsegg',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodlp670',          ['name'] = 'Rmod Murcielago LP670',                   ['brand'] = 'Rmod Keonigsegg',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodm8gte',          ['name'] = 'Rmod M8 GTE',                   ['brand'] = 'Rmod BMW',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodmartin',          ['name'] = 'Rmod DBS Superleggera',                   ['brand'] = 'Rmod Aston Martin',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodmk7',          ['name'] = 'Rmod Volkswagen Mk7',                   ['brand'] = 'Rmod Volkswagen',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodporsche918',          ['name'] = 'Rmod 918 Spyder',                   ['brand'] = 'Rmod Porsche',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodr8c',          ['name'] = 'Rmod R8',                   ['brand'] = 'Rmod Audi',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodrover',          ['name'] = 'Rmod Rover Sport V8',                   ['brand'] = 'Rmod Range Rover',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodrs6',          ['name'] = 'Rmod RS6',                   ['brand'] = 'Rmod Audi',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodsianr',          ['name'] = 'Rmod Sian Roadster',                   ['brand'] = 'Rmod Lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodskyline34',          ['name'] = 'Rmod Skyline R34',                   ['brand'] = 'Rmod Nissan',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    {['model'] = 'rmodsuprapandem',          ['name'] = 'Rmod Supra Pandem',                   ['brand'] = 'Rmod Toyota',           ['price'] = 100000,  ['categoryLabel'] = 'RMOD',       ['shop'] = 'none'},
    --- CIV (10)
    {['model'] = 'fmgt',          ['name'] = 'Mustang',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'barbiewhip2000',          ['name'] = 'barbie',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'oycklnk',          ['name'] = 'Cullinan Keyvany T1',                   ['brand'] = 'Rolls Royce',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'mk8r',          ['name'] = 'Golf Mk 8',                   ['brand'] = 'volkswagen',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'polo20',          ['name'] = 'polo',                   ['brand'] = 'volkswagen',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'amggt63',          ['name'] = 'AMGT GT63',                   ['brand'] = 'mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'lexy',          ['name'] = 'audi a9',                   ['brand'] = 'audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'e63b',          ['name'] = 'E63 Brabus',                   ['brand'] = 'Mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'r34eqilyzed',          ['name'] = 'GTR 34',                   ['brand'] = 'nissan',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'patty',          ['name'] = 'patty burger',                   ['brand'] = 'burger',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'vwstance',          ['name'] = 'Vw Passat Highline',                   ['brand'] = 'passat',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'subisti08',          ['name'] = '2008 Subaru WRX STI',                   ['brand'] = 'subaru',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'dawn',          ['name'] = '2019 Rolls Royce Dawn',                   ['brand'] = 'rolls royce',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'velar',          ['name'] = 'Range-Rover Velar 2018',                   ['brand'] = 'Range Rover',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'cayenne',          ['name'] = '2016 Porsche Cayenne Turbo S',                   ['brand'] = 'porsche',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'techart17',          ['name'] = 'Porsche Panamera Techart',                   ['brand'] = 'porsche',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'por4s',          ['name'] = '2020 Porsche 911 Cabriolet Carrera 4S',                   ['brand'] = 'porsche',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'tulenis',          ['name'] = 'Nissan Armada Nismo',                   ['brand'] = 'armada',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gclas9',          ['name'] = 'Mercedes-Benz G-Class 65 AMG',                   ['brand'] = '65 amg',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'mers63c',          ['name'] = 'Mercedes S63 AMG Cabriolet',                   ['brand'] = 's63 amg',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 's500w222',          ['name'] = 'Mercedes S500 W222',                   ['brand'] = 's500',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gsf',          ['name'] = '2019 Lexus GS F',                   ['brand'] = 'lexus gs f',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gmcs',          ['name'] = 'GMC Sierra 1500 Crew Cab All Terrain X 2017',                   ['brand'] = 'sierra',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'velociraptor',          ['name'] = '2017 Ford F-150 Hennessey Velociraptor',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gmcyd',          ['name'] = 'GMC Yukon Denali 2015',                   ['brand'] = 'gmc',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = '18f350ds',          ['name'] = '2018 Ford F-350 Dually',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = '20f250',          ['name'] = '2020 Ford F-250 Super Duty',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gt2017',          ['name'] = 'FORD GT 2017',                   ['brand'] = 'Ford',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'mgt',          ['name'] = '2004 Mustang Cobra',                   ['brand'] = 'mgt',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gtcl',          ['name'] = 'Ferrari GTC4 Lusso',                   ['brand'] = 'ferrari',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = '599gtox',          ['name'] = 'Ferrari GTO 599XX',                   ['brand'] = 'ferrari',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'bisonbutch',          ['name'] = 'Bravado Bison King-Size',                   ['brand'] = 'bravado',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'dl2016',          ['name'] = 'Dodge Ram Limited 2016 1.0',                   ['brand'] = 'dodge',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'demon',          ['name'] = '2018 Dodge Challenger SRT Demon',                   ['brand'] = 'dodge',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'camaross',          ['name'] = 'Chevrolet Camaro SS 300 Drag',                   ['brand'] = 'chevrolet',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'caprice13',          ['name'] = 'Caprice Ls 2013',                   ['brand'] = 'caprice',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'rs3s20',          ['name'] = 'RS3 Quattro',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'cats',          ['name'] = '2016 Cadillac ATS-V Coupe',                   ['brand'] = 'cadillac',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'avz',          ['name'] = '2017 Aston Martin Vanquish Zagato',                   ['brand'] = 'aston martin',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'amcj',          ['name'] = '972 AMC Javelin Ringbrothers Defiant',                   ['brand'] = 'amc',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'macanpd600m',          ['name'] = 'Macan Turbo',                   ['brand'] = 'Porsche',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'rocket',          ['name'] = 'Rocket',                   ['brand'] = 'Brabus',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'wraith',          ['name'] = 'Wraith',                   ['brand'] = 'Rolls Royce',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'toysupmk4',          ['name'] = 'Supra MK4',                   ['brand'] = 'Toyota',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'trhawk',          ['name'] = 'Trackhawk',                   ['brand'] = 'Jeep',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'twingo',          ['name'] = 'Twingo',                   ['brand'] = 'Renault',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'urus',          ['name'] = 'Urus',                   ['brand'] = 'Lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'sq72016',          ['name'] = 'SQ7 2016',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'q820',          ['name'] = 'Q8 20',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'r820',          ['name'] = 'R8 20',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'rs6',          ['name'] = 'RS6',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'RS72020',          ['name'] = 'RS7 20',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'm3e92',          ['name'] = 'MM3 E92',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'm3f80',          ['name'] = 'M3 F80',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'm4f82',          ['name'] = 'M4 F82',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'mobm23',          ['name'] = 'X7',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gtr',          ['name'] = 'GT-R',                   ['brand'] = 'Nissan',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'huracanst',          ['name'] = 'Huracan ST',                   ['brand'] = 'Lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'lp610',          ['name'] = 'Huracan LP 610',                   ['brand'] = 'Lamborghini',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'golfgti7',          ['name'] = 'Golf GTI 7',                   ['brand'] = 'Volkswagen',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'fpacehm',          ['name'] = 'F-Pace',                   ['brand'] = 'Jaguar',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'fxxk',          ['name'] = 'FXX-K',                   ['brand'] = 'Ferrari',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'G65',          ['name'] = 'Benz G-Class',                   ['brand'] = 'Mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gl63',          ['name'] = 'Benz GL63',                   ['brand'] = 'Mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'esprit02',          ['name'] = 'Esprit',                   ['brand'] = 'Lotus',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'f812',          ['name'] = 'F812',                   ['brand'] = 'Ferrari',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'cgt',          ['name'] = 'Carrera GT',                   ['brand'] = 'Porsche',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'cgts',          ['name'] = 'Continental GT',                   ['brand'] = 'Bentley',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'chiron',          ['name'] = 'Chiron',                   ['brand'] = 'Buggati',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'chr20',          ['name'] = 'SRT Hellcat',                   ['brand'] = 'Dodge Charger',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'bbentayga',          ['name'] = 'Bentayga',                   ['brand'] = 'Bentley',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'bdivo',          ['name'] = 'Divo',                   ['brand'] = 'Buggati',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'bmci',          ['name'] = 'M5',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'bmistralw16',          ['name'] = 'Mistral',                   ['brand'] = 'Buggati',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'bug09',          ['name'] = 'Veyron',                   ['brand'] = 'Buggati',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'c7',          ['name'] = 'C7',                   ['brand'] = 'Corvette',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'c6320',          ['name'] = 'E Class',                   ['brand'] = 'Mercedes Benz',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = '23m2',          ['name'] = 'M2',                   ['brand'] = 'BMW',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = '488',          ['name'] = '488',                   ['brand'] = 'Ferrari',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = '650s',          ['name'] = '650s',                   ['brand'] = 'McLaren',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = '720s',          ['name'] = '720s',                   ['brand'] = 'McLaren',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'aaq4',          ['name'] = 'A4',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'agerars',          ['name'] = 'Agera',                   ['brand'] = 'Keonigsegg',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'amggtrr20',          ['name'] = 'AMG GT',                   ['brand'] = 'Mercedes',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'a6tfsi',          ['name'] = 'A6',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    {['model'] = 'gresley',          ['name'] = 'Q7',                   ['brand'] = 'Audi',           ['price'] = 100000,  ['categoryLabel'] = 'CIV',       ['shop'] = 'none'},
    --- LUXURYCARS (11)
    {['model'] = 'cullinan',          ['name'] = 'Cullinan Keyvany T2',                   ['brand'] = 'Rolls Royce',           ['price'] = 100000,  ['categoryLabel'] = 'LUXURYCARS',       ['shop'] = 'none'},
    {['model'] = '911rwb',          ['name'] = 'Porsche 911 (993) RWB Rotana 1993',                   ['brand'] = 'porsche',           ['price'] = 100000,  ['categoryLabel'] = 'LUXURYCARS',       ['shop'] = 'none'},
    {['model'] = 'corvettezr1',          ['name'] = 'Chevrolet Corvette ZR1',                   ['brand'] = 'chevrolet',           ['price'] = 100000,  ['categoryLabel'] = 'LUXURYCARS',       ['shop'] = 'none'},
    {['model'] = 'x6m',          ['name'] = 'bmw x6',                   ['brand'] = 'bmw',           ['price'] = 100000,  ['categoryLabel'] = 'LUXURYCARS',       ['shop'] = 'none'},
    --- 1of1 (12)
    {['model'] = 'st',          ['name'] = '1of1 Ford Focus ST',                   ['brand'] = '1of1',           ['price'] = 100000,  ['categoryLabel'] = '1of1',       ['shop'] = 'none'},
    {['model'] = 'fnfcivic',          ['name'] = '1of1 1993 Honda Civic',                   ['brand'] = '1of1',           ['price'] = 100000,  ['categoryLabel'] = '1of1',       ['shop'] = 'none'},
    {['model'] = 'topfoil',          ['name'] = '1of4 Gang Evo Kray',                   ['brand'] = '1of4',           ['price'] = 100000,  ['categoryLabel'] = '1of1',       ['shop'] = 'none'},
}

for i=1, #Vehicles do
    QBShared.Vehicles[Vehicles[i].model] = {
        spawncode = Vehicles[i].model,
        name = Vehicles[i].name,
        brand = Vehicles[i].brand,
        model = Vehicles[i].model,
        price = Vehicles[i].price,
        category = Vehicles[i].categoryLabel:gsub("%s+", ""):lower(),
        categoryLabel = Vehicles[i].categoryLabel,
        hash = joaat(Vehicles[i].model),
        shop = Vehicles[i].shop
    }
end