INSERT INTO `items` (`name`, `label`) VALUES
 ('acapulcogold_seed', 'Acapulco Gold Seed'),
 ('gelato41_seed', 'Gelato 41 Seed'),
 ('acapulcogold_leaf', 'Acapulco Gold Leaf'),
 ('skunk1_seed', 'Skunk 1 Seed'),
 ('ogkush_untrimmed_bud', 'OG Kush Un-Trimmed Bud'),
 ('ogkush_trimmed_bud', 'OG Kush Trimmed Bud'),
 ('colombiangold_seed', 'Colombian Gold Seed'),
 ('weed_grow_light1', 'Grow Light'),
 ('northernlights_seed', 'Northern Lights Seed'),
 ('ogkush_leaf', 'OG Kush Leaf'),
 ('gelato41_trimmed_bud', 'Gelato 41 Trimmed Bud'),
 ('skunk1_leaf', 'Skunk 1 Leaf'),
 ('lowqualitysoil', 'Soil (LQ)'),
 ('lemonskunk_untrimmed_bud', 'Lemon Skunk Un-Trimmed Bud'),
 ('rainbowbelts_trimmed_bud', 'Rainbow Belts Trimmed Bud'),
 ('pureafghani_leaf', 'Pure Afghani Leaf'),
 ('gelato41_untrimmed_bud', 'Gelato 41 Un-Trimmed Bud'),
 ('stardawg_untrimmed_bud', 'Star Dawg Un-Trimmed Bud'),
 ('dosidos_untrimmed_bud', 'DosiDos Un-Trimmed Bud'),
 ('rainbowbelts_leaf', 'Rainbow Belts Leaf'),
 ('gelato41_leaf', 'Gelato 41 Leaf'),
 ('hiqualnutrients', 'Growing Nutrients (HQ)'),
 ('lemonskunk_trimmed_bud', 'Lemon Skunk Trimmed Bud'),
 ('pureafghani_trimmed_bud', 'Pure Afghani Trimmed Bud'),
 ('colombiangold_leaf', 'Colombian Gold Leaf'),
 ('stardawg_trimmed_bud', 'Star Dawg Trimmed Bud'),
 ('colombiangold_trimmed_bud', 'Colombian Gold Trimmed Bud'),
 ('skunk1_untrimmed_bud', 'Skunk 1 Un-Trimmed Bud'),
 ('rainbowbelts_untrimmed_bud', 'Rainbow Belts Un-Trimmed Bud'),
 ('dosidos_seed', 'DosiDos Seed'),
 ('stardawg_leaf', 'Star Dawg Leaf'),
 ('dosidos_trimmed_bud', 'DosiDos Trimmed Bud'),
 ('lemonskunk_seed', 'Lemon Skunk Seed'),
 ('northernlights_untrimmed_bud', 'Northern Lights Un-Trimmed Bud'),
 ('northernlights_trimmed_bud', 'Northern Lights Trimmed Bud'),
 ('pureafghani_seed', 'Pure Afghani Seed'),
 ('plantpot', 'Plant Pot'),
 ('lemonskunk_leaf', 'Lemon Skunk Leaf'),
 ('ogkush_seed', 'OG Kush Seed'),
 ('wateringcan', 'Watering Can'),
 ('lowqualnutrients', 'Growing Nutrients (LQ)'),
 ('acapulcogold_trimmed_bud', 'Acapulco Gold Trimmed Bud'),
 ('scissors', 'Scissors'),
 ('colombiangold_untrimmed_bud', 'Colombian Gold Un-Trimmed Bud'),
 ('medqualnutrients', 'Growing Nutrients (MQ)'),
 ('weed_grow_fan1', 'Grow Fan'),
 ('acapulcogold_untrimmed_bud', 'Acapulco Gold Un-Trimmed Bud'),
 ('stardawg_seed', 'Star Dawg Seed'),
 ('hiqualitysoil', 'Soil (HQ)'),
 ('skunk1_trimmed_bud', 'Skunk 1 Trimmed Bud'),
 ('pureafghani_untrimmed_bud', 'Pure Afghani Un-Trimmed Bud'),
 ('rainbowbelts_seed', 'Rainbow Belts Seed'),
 ('dosidos_leaf', 'DosiDos Leaf'),
 ('northernlights_leaf', 'Northern Lights Leaf'),;