['northernlights_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'northernlights_trimmed_bud',
  ['image'] = 'northernlights_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Northern Lights Trimmed Bud',
  ['description'] = 'Northern Lights trimmed bud',
  ['type'] = 'item',

},
['acapulcogold_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'acapulcogold_trimmed_bud',
  ['image'] = 'acapulcogold_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Acapulco Gold Trimmed Bud',
  ['description'] = 'Acapulco Gold trimmed bud',
  ['type'] = 'item',

},
['rainbowbelts_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'rainbowbelts_untrimmed_bud',
  ['image'] = 'rainbowbelts_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Rainbow Belts Un-Trimmed Bud',
  ['description'] = 'Rainbow Belts un-trimmed bud',
  ['type'] = 'item',

},
['hiqualitysoil'] = {
  ['shouldClose'] = false,
  ['name'] = 'hiqualitysoil',
  ['image'] = 'hiqualitysoil.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Soil (HQ)',
  ['description'] = 'Soil for your plants',
  ['type'] = 'item',

},
['weed_grow_fan1'] = {
  ['shouldClose'] = true,
  ['name'] = 'weed_grow_fan1',
  ['image'] = 'weed_grow_fan1.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['remove'] = false,
  ['label'] = 'Grow Fan',
  ['description'] = 'A fan used to cool things',
  ['type'] = 'item',

},
['acapulcogold_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'acapulcogold_leaf',
  ['image'] = 'acapulcogold_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Acapulco Gold Leaf',
  ['description'] = 'Acapulco Gold leaf',
  ['type'] = 'item',

},
['gelato41_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'gelato41_leaf',
  ['image'] = 'gelato41_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Gelato 41 Leaf',
  ['description'] = 'Gelato 41 leaf',
  ['type'] = 'item',

},
['colombiangold_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'colombiangold_seed',
  ['image'] = 'colombiangold_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Colombian Gold Seed',
  ['description'] = 'Colombian Gold AKA Santa Marta is a landrace strain from the Santa Marta mountains of Colombia.Growing in warm climate,it needs temps between 25-35 and a light spectrum higher than 35%. Soil quality minimum should be 30%',
  ['type'] = 'item',

},
['gelato41_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'gelato41_seed',
  ['image'] = 'gelato41_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Gelato 41 Seed',
  ['description'] = 'Gelato 41 is made by crossing Sunset Sherbert and Thin Mint Cookies.This strain has buds that grow in an array of colors, from light green to purple, with trichomes that put out a sweet and earthy aroma alongside hints of lavender and pine.Not easy to grow so make sure to keep temps at 19-28 and light spectrum higher than 50%. Soil quality minimum should be 70%',
  ['type'] = 'item',

},
['lemonskunk_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'lemonskunk_leaf',
  ['image'] = 'lemonskunk_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Lemon Skunk Leaf',
  ['description'] = 'Lemon Skunk leaf',
  ['type'] = 'item',

},
['colombiangold_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'colombiangold_leaf',
  ['image'] = 'colombiangold_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Colombian Gold Leaf',
  ['description'] = 'Colombian Gold leaf',
  ['type'] = 'item',

},
['colombiangold_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'colombiangold_trimmed_bud',
  ['image'] = 'colombiangold_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Colombian Gold Trimmed Bud',
  ['description'] = 'Colombian Gold trimmed bud',
  ['type'] = 'item',

},
['lemonskunk_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'lemonskunk_untrimmed_bud',
  ['image'] = 'lemonskunk_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Lemon Skunk Un-Trimmed Bud',
  ['description'] = 'Lemon Skunk un-trimmed bud',
  ['type'] = 'item',

},
['ogkush_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'ogkush_trimmed_bud',
  ['image'] = 'ogkush_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'OG Kush Trimmed Bud',
  ['description'] = 'OG Kush trimmed bud',
  ['type'] = 'item',

},
['scissors'] = {
  ['shouldClose'] = false,
  ['name'] = 'scissors',
  ['image'] = 'scissors.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Scissors',
  ['description'] = 'Used to trim things',
  ['type'] = 'item',

},
['lowqualnutrients'] = {
  ['shouldClose'] = false,
  ['name'] = 'lowqualnutrients',
  ['image'] = 'lowqualnutrients.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Growing Nutrients (LQ)',
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['type'] = 'item',

},
['wateringcan'] = {
  ['shouldClose'] = false,
  ['name'] = 'wateringcan',
  ['image'] = 'wateringcan.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['remove'] = false,
  ['label'] = 'Watering Can',
  ['description'] = 'Used to water plants',
  ['type'] = 'item',

},
['ogkush_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'ogkush_untrimmed_bud',
  ['image'] = 'ogkush_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'OG Kush Un-Trimmed Bud',
  ['description'] = 'OG Kush un-trimmed bud',
  ['type'] = 'item',

},
['pureafghani_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'pureafghani_trimmed_bud',
  ['image'] = 'pureafghani_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Pure Afghani Trimmed Bud',
  ['description'] = 'Pure Afghani trimmed bud',
  ['type'] = 'item',

},
['ogkush_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'ogkush_seed',
  ['image'] = 'ogkush_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'OG Kush Seed',
  ['description'] = 'One of the most famous and best strains to ever be created.OG Kush still stands strong with crazy gas terps and potency that can make u think twice before taking another hit.Keep temps around 20-30 and light spectrum higher than 40%. Soil quality minimum should be 50%',
  ['type'] = 'item',

},
['skunk1_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'skunk1_trimmed_bud',
  ['image'] = 'skunk1_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Skunk 1 Trimmed Bud',
  ['description'] = 'Skunk 1 trimmed bud',
  ['type'] = 'item',

},
['rainbowbelts_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'rainbowbelts_trimmed_bud',
  ['image'] = 'rainbowbelts_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Rainbow Belts Trimmed Bud',
  ['description'] = 'Rainbow Belts trimmed bud',
  ['type'] = 'item',

},
['colombiangold_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'colombiangold_untrimmed_bud',
  ['image'] = 'colombiangold_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Colombian Gold Un-Trimmed Bud',
  ['description'] = 'Colombian Gold un-trimmed bud',
  ['type'] = 'item',

},
['rainbowbelts_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'rainbowbelts_leaf',
  ['image'] = 'rainbowbelts_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Rainbow Belts Leaf',
  ['description'] = 'Rainbow Belts leaf',
  ['type'] = 'item',

},
['plantpot'] = {
  ['shouldClose'] = true,
  ['name'] = 'plantpot',
  ['image'] = 'plantpot.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Plant Pot',
  ['description'] = 'Used to Plant Pot',
  ['type'] = 'item',

},
['northernlights_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'northernlights_untrimmed_bud',
  ['image'] = 'northernlights_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Northern Lights Un-Trimmed Bud',
  ['description'] = 'Northern Lights un-trimmed bud',
  ['type'] = 'item',

},
['skunk1_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'skunk1_leaf',
  ['image'] = 'skunk1_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Skunk 1 Leaf',
  ['description'] = 'Skunk 1 leaf',
  ['type'] = 'item',

},
['dosidos_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'dosidos_trimmed_bud',
  ['image'] = 'dosidos_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'DosiDos Trimmed Bud',
  ['description'] = 'DosiDos trimmed bud',
  ['type'] = 'item',

},
['skunk1_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'skunk1_untrimmed_bud',
  ['image'] = 'skunk1_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Skunk 1 Un-Trimmed Bud',
  ['description'] = 'Skunk 1 un-trimmed bud',
  ['type'] = 'item',

},
['stardawg_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'stardawg_leaf',
  ['image'] = 'stardawg_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Star Dawg Leaf',
  ['description'] = 'Star Dawg leaf',
  ['type'] = 'item',

},
['pureafghani_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'pureafghani_leaf',
  ['image'] = 'pureafghani_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Pure Afghani Leaf',
  ['description'] = 'Pure Afghani leaf',
  ['type'] = 'item',

},
['stardawg_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'stardawg_trimmed_bud',
  ['image'] = 'stardawg_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Star Dawg Trimmed Bud',
  ['description'] = 'Star Dawg trimmed bud',
  ['type'] = 'item',

},
['ogkush_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'ogkush_leaf',
  ['image'] = 'ogkush_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'OG Kush Leaf',
  ['description'] = 'OG Kush leaf',
  ['type'] = 'item',

},
['northernlights_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'northernlights_leaf',
  ['image'] = 'northernlights_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Northern Lights Leaf',
  ['description'] = 'Northern Lights leaf',
  ['type'] = 'item',

},
['northernlights_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'northernlights_seed',
  ['image'] = 'northernlights_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Northern Lights Seed',
  ['description'] = 'Northern Lights is an amazing combination of genetics that is extremely pleasurable to smoke, with a high that is not as heavy and has a really tropical scent. Temps should be kept around 20-28 and light spectrum higher than 30%. Soil quality minimum should be 50%',
  ['type'] = 'item',

},
['acapulcogold_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'acapulcogold_untrimmed_bud',
  ['image'] = 'acapulcogold_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Acapulco Gold Un-Trimmed Bud',
  ['description'] = 'Acapulco Gold un-trimmed bud',
  ['type'] = 'item',

},
['medqualnutrients'] = {
  ['shouldClose'] = false,
  ['name'] = 'medqualnutrients',
  ['image'] = 'medqualNutrients.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Growing Nutrients (MQ)',
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['type'] = 'item',

},
['dosidos_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'dosidos_seed',
  ['image'] = 'dosidos_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'DosiDos Seed',
  ['description'] = 'With glittering trichomes, bright pistils, and lime green and lavender leaves, Dosidos weed is a feast for the eyes. Its aroma is pungent, sweet, and earthy with slight floral funkiness. Temps should be kept at 20-30 and light spectrum higher than 40%. Soil quality minimum should be 50%',
  ['type'] = 'item',

},
['weed_grow_light1'] = {
  ['shouldClose'] = true,
  ['name'] = 'weed_grow_light1',
  ['image'] = 'weed_grow_light1.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['remove'] = false,
  ['label'] = 'Grow Light',
  ['description'] = 'A light used to grow tomateos',
  ['type'] = 'item',

},
['dosidos_leaf'] = {
  ['shouldClose'] = false,
  ['name'] = 'dosidos_leaf',
  ['image'] = 'dosidos_leaf.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'DosiDos Leaf',
  ['description'] = 'DosiDos leaf',
  ['type'] = 'item',

},
['rainbowbelts_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'rainbowbelts_seed',
  ['image'] = 'rainbowbelts_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Rainbow Belts Seed',
  ['description'] = 'The flavor and aroma of this strain may remind you of sweet and fruity candy.A real exotic plant with great potency and amazing entourage effect.Temperatures should be kept between 18-26 and light spectrum higher than 45%. Soil quality minimum should be 65%',
  ['type'] = 'item',

},
['lowqualitysoil'] = {
  ['shouldClose'] = false,
  ['name'] = 'lowqualitysoil',
  ['image'] = 'lowqualitysoil.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Soil (LQ)',
  ['description'] = 'Soil for your plants',
  ['type'] = 'item',

},
['pureafghani_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'pureafghani_untrimmed_bud',
  ['image'] = 'pureafghani_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Pure Afghani Un-Trimmed Bud',
  ['description'] = 'Pure Afghani un-trimmed bud',
  ['type'] = 'item',

},
['lemonskunk_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'lemonskunk_seed',
  ['image'] = 'lemonskunk_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Lemon Skunk Seed',
  ['description'] = 'This classic strain is known to produce energizing effects with a mellow high.In terms of flavor, Lemon Skunk is skunky with a pungent aroma and exceptionally zesty lemon undertones. Keep temps around 20-32 and light spectrum higher than 20%. Soil quality minimum should be 30%',
  ['type'] = 'item',

},
['skunk1_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'skunk1_seed',
  ['image'] = 'skunk1_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Skunk 1 Seed',
  ['description'] = 'An Indica Dominant IBL Strain with great potency and amazing yields! One of the most stabilised strains and beginner friendly. Temps of 25-30 are ideal and light spectum higher than 35%. Soil quality minimum should be 35%',
  ['type'] = 'item',

},
['gelato41_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'gelato41_trimmed_bud',
  ['image'] = 'gelato41_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Gelato 41 Trimmed Bud',
  ['description'] = 'Gelato 41 trimmed bud',
  ['type'] = 'item',

},
['acapulcogold_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'acapulcogold_seed',
  ['image'] = 'acapulcogold_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Acapulco Gold Seed',
  ['description'] = 'Straight from the Guerrero Mountains of Mexico Acapulco Gold is a legendary strain with high great terpine profile and a distinct golden hue.It needs high temps between 28-35 and light spectum higher than 40%. Soil quality minimum should be 20%',
  ['type'] = 'item',

},
['stardawg_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'stardawg_untrimmed_bud',
  ['image'] = 'stardawg_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Star Dawg Un-Trimmed Bud',
  ['description'] = 'Star Dawg un-trimmed bud',
  ['type'] = 'item',

},
['stardawg_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'stardawg_seed',
  ['image'] = 'stardawg_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Star Dawg Seed',
  ['description'] = 'Made in the UK original Staw Dawg.It needs high temps between 20-30 and light spectum higher than 30%. Soil quality minimum should be 20%',
  ['type'] = 'item',

},
['dosidos_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'dosidos_untrimmed_bud',
  ['image'] = 'dosidos_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'DosiDos Un-Trimmed Bud',
  ['description'] = 'DosiDos un-trimmed bud',
  ['type'] = 'item',

},
['pureafghani_seed'] = {
  ['shouldClose'] = false,
  ['name'] = 'pureafghani_seed',
  ['image'] = 'pureafghani_seed.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Pure Afghani Seed',
  ['description'] = 'Pure Afghani hails from the Hindu Kush mountain region on the border between Afghanistan and Pakistan.Heavy body effect and great earthy terpene profile. Temperatures should be kept 15-30 with a light spectrum of around 40%',
  ['type'] = 'item',

},
['gelato41_untrimmed_bud'] = {
  ['shouldClose'] = true,
  ['name'] = 'gelato41_untrimmed_bud',
  ['image'] = 'gelato41_untrimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = true,
  ['unique'] = false,
  ['label'] = 'Gelato 41 Un-Trimmed Bud',
  ['description'] = 'Gelato 41 un-trimmed bud',
  ['type'] = 'item',

},
['hiqualnutrients'] = {
  ['shouldClose'] = false,
  ['name'] = 'hiqualnutrients',
  ['image'] = 'hiqualnutrients.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Growing Nutrients (HQ)',
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['type'] = 'item',

},
['lemonskunk_trimmed_bud'] = {
  ['shouldClose'] = false,
  ['name'] = 'lemonskunk_trimmed_bud',
  ['image'] = 'lemonskunk_trimmed_bud.png',
  ['weight'] = 0,
  ['useable'] = false,
  ['unique'] = false,
  ['label'] = 'Lemon Skunk Trimmed Bud',
  ['description'] = 'Lemon Skunk trimmed bud',
  ['type'] = 'item',

},
