['ogkush_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'ogkush_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'OG Kush trimmed bud',
  ['useable'] = false,
  ['label'] = 'OG Kush Trimmed Bud',
  ['image'] = 'ogkush_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['northernlights_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'northernlights_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Northern Lights un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Northern Lights Un-Trimmed Bud',
  ['image'] = 'northernlights_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['acapulcogold_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'acapulcogold_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Acapulco Gold trimmed bud',
  ['useable'] = false,
  ['label'] = 'Acapulco Gold Trimmed Bud',
  ['image'] = 'acapulcogold_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['colombiangold_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'colombiangold_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Colombian Gold trimmed bud',
  ['useable'] = false,
  ['label'] = 'Colombian Gold Trimmed Bud',
  ['image'] = 'colombiangold_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['rainbowbelts_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Rainbow Belts trimmed bud',
  ['useable'] = false,
  ['label'] = 'Rainbow Belts Trimmed Bud',
  ['image'] = 'rainbowbelts_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['weed_grow_light1'] = {
  ['type'] = 'item',
  ['name'] = 'weed_grow_light1',
  ['useable'] = true,
  ['description'] = 'A light used to grow tomateos',
  ['unique'] = false,
  ['remove'] = false,
  ['label'] = 'Grow Light',
  ['image'] = 'weed_grow_light1.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['ogkush_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'ogkush_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'OG Kush un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'OG Kush Un-Trimmed Bud',
  ['image'] = 'ogkush_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['stardawg_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'stardawg_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Star Dawg trimmed bud',
  ['useable'] = false,
  ['label'] = 'Star Dawg Trimmed Bud',
  ['image'] = 'stardawg_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['colombiangold_seed'] = {
  ['type'] = 'item',
  ['name'] = 'colombiangold_seed',
  ['unique'] = false,
  ['description'] = 'Colombian Gold AKA Santa Marta is a landrace strain from the Santa Marta mountains of Colombia.Growing in warm climate,it needs temps between 25-35 and a light spectrum higher than 35%. Soil quality minimum should be 30%',
  ['useable'] = false,
  ['label'] = 'Colombian Gold Seed',
  ['image'] = 'colombiangold_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['northernlights_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'northernlights_leaf',
  ['unique'] = false,
  ['description'] = 'Northern Lights leaf',
  ['useable'] = false,
  ['label'] = 'Northern Lights Leaf',
  ['image'] = 'northernlights_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['lemonskunk_seed'] = {
  ['type'] = 'item',
  ['name'] = 'lemonskunk_seed',
  ['unique'] = false,
  ['description'] = 'This classic strain is known to produce energizing effects with a mellow high.In terms of flavor, Lemon Skunk is skunky with a pungent aroma and exceptionally zesty lemon undertones. Keep temps around 20-32 and light spectrum higher than 20%. Soil quality minimum should be 30%',
  ['useable'] = false,
  ['label'] = 'Lemon Skunk Seed',
  ['image'] = 'lemonskunk_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['ogkush_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'ogkush_leaf',
  ['unique'] = false,
  ['description'] = 'OG Kush leaf',
  ['useable'] = false,
  ['label'] = 'OG Kush Leaf',
  ['image'] = 'ogkush_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['dosidos_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'dosidos_leaf',
  ['unique'] = false,
  ['description'] = 'DosiDos leaf',
  ['useable'] = false,
  ['label'] = 'DosiDos Leaf',
  ['image'] = 'dosidos_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['ogkush_seed'] = {
  ['type'] = 'item',
  ['name'] = 'ogkush_seed',
  ['unique'] = false,
  ['description'] = 'One of the most famous and best strains to ever be created.OG Kush still stands strong with crazy gas terps and potency that can make u think twice before taking another hit.Keep temps around 20-30 and light spectrum higher than 40%. Soil quality minimum should be 50%',
  ['useable'] = false,
  ['label'] = 'OG Kush Seed',
  ['image'] = 'ogkush_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['pureafghani_seed'] = {
  ['type'] = 'item',
  ['name'] = 'pureafghani_seed',
  ['unique'] = false,
  ['description'] = 'Pure Afghani hails from the Hindu Kush mountain region on the border between Afghanistan and Pakistan.Heavy body effect and great earthy terpene profile. Temperatures should be kept 15-30 with a light spectrum of around 40%',
  ['useable'] = false,
  ['label'] = 'Pure Afghani Seed',
  ['image'] = 'pureafghani_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['acapulcogold_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'acapulcogold_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Acapulco Gold un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Acapulco Gold Un-Trimmed Bud',
  ['image'] = 'acapulcogold_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['lemonskunk_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'lemonskunk_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Lemon Skunk un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Lemon Skunk Un-Trimmed Bud',
  ['image'] = 'lemonskunk_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['gelato41_seed'] = {
  ['type'] = 'item',
  ['name'] = 'gelato41_seed',
  ['unique'] = false,
  ['description'] = 'Gelato 41 is made by crossing Sunset Sherbert and Thin Mint Cookies.This strain has buds that grow in an array of colors, from light green to purple, with trichomes that put out a sweet and earthy aroma alongside hints of lavender and pine.Not easy to grow so make sure to keep temps at 19-28 and light spectrum higher than 50%. Soil quality minimum should be 70%',
  ['useable'] = false,
  ['label'] = 'Gelato 41 Seed',
  ['image'] = 'gelato41_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['northernlights_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'northernlights_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Northern Lights trimmed bud',
  ['useable'] = false,
  ['label'] = 'Northern Lights Trimmed Bud',
  ['image'] = 'northernlights_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['dosidos_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'dosidos_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'DosiDos trimmed bud',
  ['useable'] = false,
  ['label'] = 'DosiDos Trimmed Bud',
  ['image'] = 'dosidos_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['gelato41_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'gelato41_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Gelato 41 trimmed bud',
  ['useable'] = false,
  ['label'] = 'Gelato 41 Trimmed Bud',
  ['image'] = 'gelato41_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['dosidos_seed'] = {
  ['type'] = 'item',
  ['name'] = 'dosidos_seed',
  ['unique'] = false,
  ['description'] = 'With glittering trichomes, bright pistils, and lime green and lavender leaves, Dosidos weed is a feast for the eyes. Its aroma is pungent, sweet, and earthy with slight floral funkiness. Temps should be kept at 20-30 and light spectrum higher than 40%. Soil quality minimum should be 50%',
  ['useable'] = false,
  ['label'] = 'DosiDos Seed',
  ['image'] = 'dosidos_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['hiqualitysoil'] = {
  ['type'] = 'item',
  ['name'] = 'hiqualitysoil',
  ['unique'] = false,
  ['description'] = 'Soil for your plants',
  ['useable'] = false,
  ['label'] = 'Soil (HQ)',
  ['image'] = 'hiqualitysoil.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['colombiangold_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'colombiangold_leaf',
  ['unique'] = false,
  ['description'] = 'Colombian Gold leaf',
  ['useable'] = false,
  ['label'] = 'Colombian Gold Leaf',
  ['image'] = 'colombiangold_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['rainbowbelts_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Rainbow Belts un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Rainbow Belts Un-Trimmed Bud',
  ['image'] = 'rainbowbelts_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['acapulcogold_seed'] = {
  ['type'] = 'item',
  ['name'] = 'acapulcogold_seed',
  ['unique'] = false,
  ['description'] = 'Straight from the Guerrero Mountains of Mexico Acapulco Gold is a legendary strain with high great terpine profile and a distinct golden hue.It needs high temps between 28-35 and light spectum higher than 40%. Soil quality minimum should be 20%',
  ['useable'] = false,
  ['label'] = 'Acapulco Gold Seed',
  ['image'] = 'acapulcogold_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['pureafghani_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'pureafghani_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Pure Afghani un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Pure Afghani Un-Trimmed Bud',
  ['image'] = 'pureafghani_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['pureafghani_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'pureafghani_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Pure Afghani trimmed bud',
  ['useable'] = false,
  ['label'] = 'Pure Afghani Trimmed Bud',
  ['image'] = 'pureafghani_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['rainbowbelts_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_leaf',
  ['unique'] = false,
  ['description'] = 'Rainbow Belts leaf',
  ['useable'] = false,
  ['label'] = 'Rainbow Belts Leaf',
  ['image'] = 'rainbowbelts_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['northernlights_seed'] = {
  ['type'] = 'item',
  ['name'] = 'northernlights_seed',
  ['unique'] = false,
  ['description'] = 'Northern Lights is an amazing combination of genetics that is extremely pleasurable to smoke, with a high that is not as heavy and has a really tropical scent. Temps should be kept around 20-28 and light spectrum higher than 30%. Soil quality minimum should be 50%',
  ['useable'] = false,
  ['label'] = 'Northern Lights Seed',
  ['image'] = 'northernlights_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['skunk1_seed'] = {
  ['type'] = 'item',
  ['name'] = 'skunk1_seed',
  ['unique'] = false,
  ['description'] = 'An Indica Dominant IBL Strain with great potency and amazing yields! One of the most stabilised strains and beginner friendly. Temps of 25-30 are ideal and light spectum higher than 35%. Soil quality minimum should be 35%',
  ['useable'] = false,
  ['label'] = 'Skunk 1 Seed',
  ['image'] = 'skunk1_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['dosidos_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'dosidos_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'DosiDos un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'DosiDos Un-Trimmed Bud',
  ['image'] = 'dosidos_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['stardawg_seed'] = {
  ['type'] = 'item',
  ['name'] = 'stardawg_seed',
  ['unique'] = false,
  ['description'] = 'Made in the UK original Staw Dawg.It needs high temps between 20-30 and light spectum higher than 30%. Soil quality minimum should be 20%',
  ['useable'] = false,
  ['label'] = 'Star Dawg Seed',
  ['image'] = 'stardawg_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['stardawg_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'stardawg_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Star Dawg un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Star Dawg Un-Trimmed Bud',
  ['image'] = 'stardawg_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['plantpot'] = {
  ['type'] = 'item',
  ['name'] = 'plantpot',
  ['unique'] = false,
  ['description'] = 'Used to Plant Pot',
  ['label'] = 'Plant Pot',
  ['image'] = 'plantpot.png',
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['rainbowbelts_seed'] = {
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_seed',
  ['unique'] = false,
  ['description'] = 'The flavor and aroma of this strain may remind you of sweet and fruity candy.A real exotic plant with great potency and amazing entourage effect.Temperatures should be kept between 18-26 and light spectrum higher than 45%. Soil quality minimum should be 65%',
  ['useable'] = false,
  ['label'] = 'Rainbow Belts Seed',
  ['image'] = 'rainbowbelts_seed.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['skunk1_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'skunk1_leaf',
  ['unique'] = false,
  ['description'] = 'Skunk 1 leaf',
  ['useable'] = false,
  ['label'] = 'Skunk 1 Leaf',
  ['image'] = 'skunk1_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['lemonskunk_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'lemonskunk_leaf',
  ['unique'] = false,
  ['description'] = 'Lemon Skunk leaf',
  ['useable'] = false,
  ['label'] = 'Lemon Skunk Leaf',
  ['image'] = 'lemonskunk_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['lowqualitysoil'] = {
  ['type'] = 'item',
  ['name'] = 'lowqualitysoil',
  ['unique'] = false,
  ['description'] = 'Soil for your plants',
  ['useable'] = false,
  ['label'] = 'Soil (LQ)',
  ['image'] = 'lowqualitysoil.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['lowqualnutrients'] = {
  ['type'] = 'item',
  ['name'] = 'lowqualnutrients',
  ['unique'] = false,
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['useable'] = false,
  ['label'] = 'Growing Nutrients (LQ)',
  ['image'] = 'lowqualnutrients.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['skunk1_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'skunk1_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Skunk 1 trimmed bud',
  ['useable'] = false,
  ['label'] = 'Skunk 1 Trimmed Bud',
  ['image'] = 'skunk1_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['acapulcogold_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'acapulcogold_leaf',
  ['unique'] = false,
  ['description'] = 'Acapulco Gold leaf',
  ['useable'] = false,
  ['label'] = 'Acapulco Gold Leaf',
  ['image'] = 'acapulcogold_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['pureafghani_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'pureafghani_leaf',
  ['unique'] = false,
  ['description'] = 'Pure Afghani leaf',
  ['useable'] = false,
  ['label'] = 'Pure Afghani Leaf',
  ['image'] = 'pureafghani_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['stardawg_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'stardawg_leaf',
  ['unique'] = false,
  ['description'] = 'Star Dawg leaf',
  ['useable'] = false,
  ['label'] = 'Star Dawg Leaf',
  ['image'] = 'stardawg_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['wateringcan'] = {
  ['type'] = 'item',
  ['name'] = 'wateringcan',
  ['unique'] = false,
  ['description'] = 'Used to water plants',
  ['image'] = 'wateringcan.png',
  ['remove'] = false,
  ['label'] = 'Watering Can',
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['gelato41_leaf'] = {
  ['type'] = 'item',
  ['name'] = 'gelato41_leaf',
  ['unique'] = false,
  ['description'] = 'Gelato 41 leaf',
  ['useable'] = false,
  ['label'] = 'Gelato 41 Leaf',
  ['image'] = 'gelato41_leaf.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['hiqualnutrients'] = {
  ['type'] = 'item',
  ['name'] = 'hiqualnutrients',
  ['unique'] = false,
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['useable'] = false,
  ['label'] = 'Growing Nutrients (HQ)',
  ['image'] = 'hiqualnutrients.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['colombiangold_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'colombiangold_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Colombian Gold un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Colombian Gold Un-Trimmed Bud',
  ['image'] = 'colombiangold_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['medqualnutrients'] = {
  ['type'] = 'item',
  ['name'] = 'medqualnutrients',
  ['unique'] = false,
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['useable'] = false,
  ['label'] = 'Growing Nutrients (MQ)',
  ['image'] = 'medqualNutrients.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['skunk1_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'skunk1_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Skunk 1 un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Skunk 1 Un-Trimmed Bud',
  ['image'] = 'skunk1_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['lemonskunk_trimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'lemonskunk_trimmed_bud',
  ['unique'] = false,
  ['description'] = 'Lemon Skunk trimmed bud',
  ['useable'] = false,
  ['label'] = 'Lemon Skunk Trimmed Bud',
  ['image'] = 'lemonskunk_trimmed_bud.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['scissors'] = {
  ['type'] = 'item',
  ['name'] = 'scissors',
  ['unique'] = false,
  ['description'] = 'Used to trim things',
  ['useable'] = false,
  ['label'] = 'Scissors',
  ['image'] = 'scissors.png',
  ['shouldClose'] = false,
  ['weight'] = 0,

},
['weed_grow_fan1'] = {
  ['type'] = 'item',
  ['name'] = 'weed_grow_fan1',
  ['useable'] = true,
  ['description'] = 'A fan used to cool things',
  ['unique'] = false,
  ['remove'] = false,
  ['label'] = 'Grow Fan',
  ['image'] = 'weed_grow_fan1.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
['gelato41_untrimmed_bud'] = {
  ['type'] = 'item',
  ['name'] = 'gelato41_untrimmed_bud',
  ['unique'] = false,
  ['description'] = 'Gelato 41 un-trimmed bud',
  ['useable'] = true,
  ['label'] = 'Gelato 41 Un-Trimmed Bud',
  ['image'] = 'gelato41_untrimmed_bud.png',
  ['shouldClose'] = true,
  ['weight'] = 0,

},
