['dosidos_untrimmed_bud'] = {
  ['description'] = 'DosiDos un-trimmed bud',
  ['label'] = 'DosiDos Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'dosidos_untrimmed_bud',
  ['image'] = 'dosidos_untrimmed_bud.png',

},
['ogkush_trimmed_bud'] = {
  ['description'] = 'OG Kush trimmed bud',
  ['label'] = 'OG Kush Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'ogkush_trimmed_bud',
  ['image'] = 'ogkush_trimmed_bud.png',

},
['northernlights_seed'] = {
  ['description'] = 'Northern Lights is an amazing combination of genetics that is extremely pleasurable to smoke, with a high that is not as heavy and has a really tropical scent. Temps should be kept around 20-28 and light spectrum higher than 30%. Soil quality minimum should be 50%',
  ['label'] = 'Northern Lights Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'northernlights_seed',
  ['image'] = 'northernlights_seed.png',

},
['gelato41_trimmed_bud'] = {
  ['description'] = 'Gelato 41 trimmed bud',
  ['label'] = 'Gelato 41 Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'gelato41_trimmed_bud',
  ['image'] = 'gelato41_trimmed_bud.png',

},
['wateringcan'] = {
  ['description'] = 'Used to water plants',
  ['remove'] = false,
  ['label'] = 'Watering Can',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'wateringcan',
  ['image'] = 'wateringcan.png',

},
['northernlights_leaf'] = {
  ['description'] = 'Northern Lights leaf',
  ['label'] = 'Northern Lights Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'northernlights_leaf',
  ['image'] = 'northernlights_leaf.png',

},
['pureafghani_seed'] = {
  ['description'] = 'Pure Afghani hails from the Hindu Kush mountain region on the border between Afghanistan and Pakistan.Heavy body effect and great earthy terpene profile. Temperatures should be kept 15-30 with a light spectrum of around 40%',
  ['label'] = 'Pure Afghani Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'pureafghani_seed',
  ['image'] = 'pureafghani_seed.png',

},
['northernlights_trimmed_bud'] = {
  ['description'] = 'Northern Lights trimmed bud',
  ['label'] = 'Northern Lights Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'northernlights_trimmed_bud',
  ['image'] = 'northernlights_trimmed_bud.png',

},
['ogkush_seed'] = {
  ['description'] = 'One of the most famous and best strains to ever be created.OG Kush still stands strong with crazy gas terps and potency that can make u think twice before taking another hit.Keep temps around 20-30 and light spectrum higher than 40%. Soil quality minimum should be 50%',
  ['label'] = 'OG Kush Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'ogkush_seed',
  ['image'] = 'ogkush_seed.png',

},
['lowqualitysoil'] = {
  ['description'] = 'Soil for your plants',
  ['label'] = 'Soil (LQ)',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'lowqualitysoil',
  ['image'] = 'lowqualitysoil.png',

},
['pureafghani_leaf'] = {
  ['description'] = 'Pure Afghani leaf',
  ['label'] = 'Pure Afghani Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'pureafghani_leaf',
  ['image'] = 'pureafghani_leaf.png',

},
['skunk1_leaf'] = {
  ['description'] = 'Skunk 1 leaf',
  ['label'] = 'Skunk 1 Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'skunk1_leaf',
  ['image'] = 'skunk1_leaf.png',

},
['weed_grow_fan1'] = {
  ['description'] = 'A fan used to cool things',
  ['remove'] = false,
  ['label'] = 'Grow Fan',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'weed_grow_fan1',
  ['image'] = 'weed_grow_fan1.png',

},
['lemonskunk_trimmed_bud'] = {
  ['description'] = 'Lemon Skunk trimmed bud',
  ['label'] = 'Lemon Skunk Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'lemonskunk_trimmed_bud',
  ['image'] = 'lemonskunk_trimmed_bud.png',

},
['acapulcogold_leaf'] = {
  ['description'] = 'Acapulco Gold leaf',
  ['label'] = 'Acapulco Gold Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'acapulcogold_leaf',
  ['image'] = 'acapulcogold_leaf.png',

},
['lemonskunk_untrimmed_bud'] = {
  ['description'] = 'Lemon Skunk un-trimmed bud',
  ['label'] = 'Lemon Skunk Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'lemonskunk_untrimmed_bud',
  ['image'] = 'lemonskunk_untrimmed_bud.png',

},
['ogkush_untrimmed_bud'] = {
  ['description'] = 'OG Kush un-trimmed bud',
  ['label'] = 'OG Kush Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'ogkush_untrimmed_bud',
  ['image'] = 'ogkush_untrimmed_bud.png',

},
['gelato41_untrimmed_bud'] = {
  ['description'] = 'Gelato 41 un-trimmed bud',
  ['label'] = 'Gelato 41 Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'gelato41_untrimmed_bud',
  ['image'] = 'gelato41_untrimmed_bud.png',

},
['scissors'] = {
  ['description'] = 'Used to trim things',
  ['label'] = 'Scissors',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'scissors',
  ['image'] = 'scissors.png',

},
['skunk1_seed'] = {
  ['description'] = 'An Indica Dominant IBL Strain with great potency and amazing yields! One of the most stabilised strains and beginner friendly. Temps of 25-30 are ideal and light spectum higher than 35%. Soil quality minimum should be 35%',
  ['label'] = 'Skunk 1 Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'skunk1_seed',
  ['image'] = 'skunk1_seed.png',

},
['lemonskunk_seed'] = {
  ['description'] = 'This classic strain is known to produce energizing effects with a mellow high.In terms of flavor, Lemon Skunk is skunky with a pungent aroma and exceptionally zesty lemon undertones. Keep temps around 20-32 and light spectrum higher than 20%. Soil quality minimum should be 30%',
  ['label'] = 'Lemon Skunk Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'lemonskunk_seed',
  ['image'] = 'lemonskunk_seed.png',

},
['colombiangold_untrimmed_bud'] = {
  ['description'] = 'Colombian Gold un-trimmed bud',
  ['label'] = 'Colombian Gold Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'colombiangold_untrimmed_bud',
  ['image'] = 'colombiangold_untrimmed_bud.png',

},
['stardawg_trimmed_bud'] = {
  ['description'] = 'Star Dawg trimmed bud',
  ['label'] = 'Star Dawg Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'stardawg_trimmed_bud',
  ['image'] = 'stardawg_trimmed_bud.png',

},
['lowqualnutrients'] = {
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['label'] = 'Growing Nutrients (LQ)',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'lowqualnutrients',
  ['image'] = 'lowqualnutrients.png',

},
['ogkush_leaf'] = {
  ['description'] = 'OG Kush leaf',
  ['label'] = 'OG Kush Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'ogkush_leaf',
  ['image'] = 'ogkush_leaf.png',

},
['rainbowbelts_untrimmed_bud'] = {
  ['description'] = 'Rainbow Belts un-trimmed bud',
  ['label'] = 'Rainbow Belts Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_untrimmed_bud',
  ['image'] = 'rainbowbelts_untrimmed_bud.png',

},
['colombiangold_leaf'] = {
  ['description'] = 'Colombian Gold leaf',
  ['label'] = 'Colombian Gold Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'colombiangold_leaf',
  ['image'] = 'colombiangold_leaf.png',

},
['plantpot'] = {
  ['description'] = 'Used to Plant Pot',
  ['weight'] = 0,
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['label'] = 'Plant Pot',
  ['type'] = 'item',
  ['name'] = 'plantpot',
  ['image'] = 'plantpot.png',

},
['hiqualnutrients'] = {
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['label'] = 'Growing Nutrients (HQ)',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'hiqualnutrients',
  ['image'] = 'hiqualnutrients.png',

},
['colombiangold_trimmed_bud'] = {
  ['description'] = 'Colombian Gold trimmed bud',
  ['label'] = 'Colombian Gold Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'colombiangold_trimmed_bud',
  ['image'] = 'colombiangold_trimmed_bud.png',

},
['pureafghani_untrimmed_bud'] = {
  ['description'] = 'Pure Afghani un-trimmed bud',
  ['label'] = 'Pure Afghani Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'pureafghani_untrimmed_bud',
  ['image'] = 'pureafghani_untrimmed_bud.png',

},
['rainbowbelts_trimmed_bud'] = {
  ['description'] = 'Rainbow Belts trimmed bud',
  ['label'] = 'Rainbow Belts Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_trimmed_bud',
  ['image'] = 'rainbowbelts_trimmed_bud.png',

},
['acapulcogold_untrimmed_bud'] = {
  ['description'] = 'Acapulco Gold un-trimmed bud',
  ['label'] = 'Acapulco Gold Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'acapulcogold_untrimmed_bud',
  ['image'] = 'acapulcogold_untrimmed_bud.png',

},
['stardawg_untrimmed_bud'] = {
  ['description'] = 'Star Dawg un-trimmed bud',
  ['label'] = 'Star Dawg Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'stardawg_untrimmed_bud',
  ['image'] = 'stardawg_untrimmed_bud.png',

},
['northernlights_untrimmed_bud'] = {
  ['description'] = 'Northern Lights un-trimmed bud',
  ['label'] = 'Northern Lights Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'northernlights_untrimmed_bud',
  ['image'] = 'northernlights_untrimmed_bud.png',

},
['gelato41_seed'] = {
  ['description'] = 'Gelato 41 is made by crossing Sunset Sherbert and Thin Mint Cookies.This strain has buds that grow in an array of colors, from light green to purple, with trichomes that put out a sweet and earthy aroma alongside hints of lavender and pine.Not easy to grow so make sure to keep temps at 19-28 and light spectrum higher than 50%. Soil quality minimum should be 70%',
  ['label'] = 'Gelato 41 Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'gelato41_seed',
  ['image'] = 'gelato41_seed.png',

},
['skunk1_trimmed_bud'] = {
  ['description'] = 'Skunk 1 trimmed bud',
  ['label'] = 'Skunk 1 Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'skunk1_trimmed_bud',
  ['image'] = 'skunk1_trimmed_bud.png',

},
['acapulcogold_trimmed_bud'] = {
  ['description'] = 'Acapulco Gold trimmed bud',
  ['label'] = 'Acapulco Gold Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'acapulcogold_trimmed_bud',
  ['image'] = 'acapulcogold_trimmed_bud.png',

},
['rainbowbelts_seed'] = {
  ['description'] = 'The flavor and aroma of this strain may remind you of sweet and fruity candy.A real exotic plant with great potency and amazing entourage effect.Temperatures should be kept between 18-26 and light spectrum higher than 45%. Soil quality minimum should be 65%',
  ['label'] = 'Rainbow Belts Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_seed',
  ['image'] = 'rainbowbelts_seed.png',

},
['hiqualitysoil'] = {
  ['description'] = 'Soil for your plants',
  ['label'] = 'Soil (HQ)',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'hiqualitysoil',
  ['image'] = 'hiqualitysoil.png',

},
['dosidos_seed'] = {
  ['description'] = 'With glittering trichomes, bright pistils, and lime green and lavender leaves, Dosidos weed is a feast for the eyes. Its aroma is pungent, sweet, and earthy with slight floral funkiness. Temps should be kept at 20-30 and light spectrum higher than 40%. Soil quality minimum should be 50%',
  ['label'] = 'DosiDos Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'dosidos_seed',
  ['image'] = 'dosidos_seed.png',

},
['medqualnutrients'] = {
  ['description'] = 'Used to Boost your crops soil nutrients',
  ['label'] = 'Growing Nutrients (MQ)',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'medqualnutrients',
  ['image'] = 'medqualNutrients.png',

},
['stardawg_seed'] = {
  ['description'] = 'Made in the UK original Staw Dawg.It needs high temps between 20-30 and light spectum higher than 30%. Soil quality minimum should be 20%',
  ['label'] = 'Star Dawg Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'stardawg_seed',
  ['image'] = 'stardawg_seed.png',

},
['gelato41_leaf'] = {
  ['description'] = 'Gelato 41 leaf',
  ['label'] = 'Gelato 41 Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'gelato41_leaf',
  ['image'] = 'gelato41_leaf.png',

},
['colombiangold_seed'] = {
  ['description'] = 'Colombian Gold AKA Santa Marta is a landrace strain from the Santa Marta mountains of Colombia.Growing in warm climate,it needs temps between 25-35 and a light spectrum higher than 35%. Soil quality minimum should be 30%',
  ['label'] = 'Colombian Gold Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'colombiangold_seed',
  ['image'] = 'colombiangold_seed.png',

},
['stardawg_leaf'] = {
  ['description'] = 'Star Dawg leaf',
  ['label'] = 'Star Dawg Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'stardawg_leaf',
  ['image'] = 'stardawg_leaf.png',

},
['weed_grow_light1'] = {
  ['description'] = 'A light used to grow tomateos',
  ['remove'] = false,
  ['label'] = 'Grow Light',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'weed_grow_light1',
  ['image'] = 'weed_grow_light1.png',

},
['dosidos_trimmed_bud'] = {
  ['description'] = 'DosiDos trimmed bud',
  ['label'] = 'DosiDos Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'dosidos_trimmed_bud',
  ['image'] = 'dosidos_trimmed_bud.png',

},
['acapulcogold_seed'] = {
  ['description'] = 'Straight from the Guerrero Mountains of Mexico Acapulco Gold is a legendary strain with high great terpine profile and a distinct golden hue.It needs high temps between 28-35 and light spectum higher than 40%. Soil quality minimum should be 20%',
  ['label'] = 'Acapulco Gold Seed',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'acapulcogold_seed',
  ['image'] = 'acapulcogold_seed.png',

},
['dosidos_leaf'] = {
  ['description'] = 'DosiDos leaf',
  ['label'] = 'DosiDos Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'dosidos_leaf',
  ['image'] = 'dosidos_leaf.png',

},
['rainbowbelts_leaf'] = {
  ['description'] = 'Rainbow Belts leaf',
  ['label'] = 'Rainbow Belts Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'rainbowbelts_leaf',
  ['image'] = 'rainbowbelts_leaf.png',

},
['lemonskunk_leaf'] = {
  ['description'] = 'Lemon Skunk leaf',
  ['label'] = 'Lemon Skunk Leaf',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'lemonskunk_leaf',
  ['image'] = 'lemonskunk_leaf.png',

},
['skunk1_untrimmed_bud'] = {
  ['description'] = 'Skunk 1 un-trimmed bud',
  ['label'] = 'Skunk 1 Un-Trimmed Bud',
  ['unique'] = false,
  ['useable'] = true,
  ['shouldClose'] = true,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'skunk1_untrimmed_bud',
  ['image'] = 'skunk1_untrimmed_bud.png',

},
['pureafghani_trimmed_bud'] = {
  ['description'] = 'Pure Afghani trimmed bud',
  ['label'] = 'Pure Afghani Trimmed Bud',
  ['unique'] = false,
  ['useable'] = false,
  ['shouldClose'] = false,
  ['weight'] = 0,
  ['type'] = 'item',
  ['name'] = 'pureafghani_trimmed_bud',
  ['image'] = 'pureafghani_trimmed_bud.png',

},
