Config = {}

Config.Debug = true

Config.Language = "en"

Config.DeathDropsWeapon = false -- Drops your current weapon upon death.

Config.ThrowKeybind = "k"

Config.Weapons = { -- Any weapon in this list is throwable.
    "WEAPON_DAGGER",

    "WEAPON_BAT",

    "WEAPON_BOTTLE",

    "WEAPON_CROWBAR",

    "WEAPON_GOLFCLUB",

    "WEAPON_HAMMER",

    "WEAPON_HATCHET",

    "WEAPON_KNUCKLE",

    "WEAPON_KNIFE",

    "WEAPON_MACHETE",

    "WEAPON_SWITCHBLADE",

    "WEAPON_WRENCH",

    "WEAPON_BATTLEAXE",

    "WEAPON_POOLCUE",

    "WEAPON_STONE_HATCHET",

    "WEAPON_PISTOL",

    "WEAPON_COMBATPISTOL",

    "WEAPON_APPISTOL",

    "WEAPON_PISTOL50",

    "WEAPON_SNSPISTOL",

    "WEAPON_HEAVYPISTOL",

    "WEAPON_VINTAGEPISTOL",

    "WEAPON_FLAREGUN",

    "WEAPON_MARKSMANPISTOL",

    "WEAPON_REVOLVER",

    "WEAPON_DOUBLEACTION",

    "WEAPON_RAYPISTOL",

    "WEAPON_CERAMICPISTOL",

    "WEAPON_NAVYREVOLVER",

    "WEAPON_MICROSMG",

    "WEAPON_SMG",

    "WEAPON_ASSAULTSMG",

    "WEAPON_COMBATPDW",

    "WEAPON_MACHINEPISTOL",

    "WEAPON_MINISMG",

    "WEAPON_RAYCARBINE",

    "WEAPON_PUMPSHOTGUN",

    "WEAPON_SAWNOFFSHOTGUN",

    "WEAPON_ASSAULTSHOTGUN",

    "WEAPON_BULLPUPSHOTGUN",

    "WEAPON_MUSKET",

    "WEAPON_HEAVYSHOTGUN",

    "WEAPON_DBSHOTGUN",

    "WEAPON_AUTOSHOTGUN",

    "WEAPON_ASSAULTRIFLE",

    "WEAPON_CARBINERIFLE",

    "WEAPON_ADVANCEDRIFLE",

    "WEAPON_SPECIALCARBINE",

    "WEAPON_BULLPUPRIFLE",

    "WEAPON_COMPACTRIFLE",

    "WEAPON_MG",

    "WEAPON_COMBATMG",

    "WEAPON_GUSENBERG",

    "WEAPON_SNIPERRIFLE",
	
    "WEAPON_HEAVYSNIPER",

    "WEAPON_MARKSMANRIFLE",

    "WEAPON_RPG",

    "WEAPON_GRENADELAUNCHER",

    "WEAPON_GRENADELAUNCHER_SMOKE",

    "WEAPON_MINIGUN",

    "WEAPON_FIREWORK",

    "WEAPON_RAILGUN",

    "WEAPON_HOMINGLAUNCHER",

    "WEAPON_COMPACTLAUNCHER",

    "WEAPON_RAYMINIGUN",

	-- Police
	--[[
    "WEAPON_MARKSMANRIFLE_MK2",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_BULLPUPRIFLE_MK2",
    "WEAPON_SPECIALCARBINE_MK2",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_PUMPSHOTGUN_MK2",
    "WEAPON_SMG_MK2",
    "WEAPON_REVOLVER_MK2",
    "WEAPON_STUNGUN",
    "WEAPON_SNSPISTOL_MK2",
    "WEAPON_PISTOL_MK2",
    "WEAPON_FLASHLIGHT",
	"WEAPON_NIGHTSTICK",
	]]
}