['cutcocaine'] = {
  ['useable'] = false,
  ['name'] = 'cutcocaine',
  ['image'] = 'cutcocaine.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Cut Cocaine',
  ['label'] = 'Cut Cocaine',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['trimmed_weed'] = {
  ['useable'] = false,
  ['name'] = 'trimmed_weed',
  ['image'] = 'trimmed_weed.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Trimmed Weed',
  ['label'] = 'Trimmed Weed',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['raidtool'] = {
  ['useable'] = false,
  ['name'] = 'raidtool',
  ['image'] = 'raidtool.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'For beating the shit out of doors',
  ['label'] = 'Raid Tool',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['untrimmed_weed'] = {
  ['useable'] = false,
  ['name'] = 'untrimmed_weed',
  ['image'] = 'untrimmed_weed.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Untrimmed Weed',
  ['label'] = 'Untrimmed Weed',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['lab-key'] = {
  ['useable'] = true,
  ['name'] = 'lab-key',
  ['image'] = 'labkeys.png',
  ['unique'] = true,
  ['type'] = 'item',
  ['description'] = 'Keys for some sort of door?!?!',
  ['label'] = 'Lab Keys',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['bakingsoda'] = {
  ['useable'] = false,
  ['name'] = 'bakingsoda',
  ['image'] = 'bakingsoda.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Baking Soda',
  ['label'] = 'Baking Soda',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['cocainepackage'] = {
  ['useable'] = false,
  ['name'] = 'cocainepackage',
  ['image'] = 'cocainepackage.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'A small figurine filled with a white powdery substance...',
  ['label'] = 'Cocaine Package',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['rawcocaine'] = {
  ['useable'] = false,
  ['name'] = 'rawcocaine',
  ['image'] = 'rawcocaine.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Uncut Cocaine',
  ['label'] = 'Raw Cocaine',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['sodiumbenzoate'] = {
  ['useable'] = false,
  ['name'] = 'sodiumbenzoate',
  ['image'] = 'sodiumbenzoate.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Chemical Substance',
  ['label'] = 'Sodium Benzoate',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['propelyeneglycol'] = {
  ['useable'] = false,
  ['name'] = 'propelyeneglycol',
  ['image'] = 'propelyeneglycol.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Chemical Substance',
  ['label'] = 'Propelyene Glycol',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['actionfigure'] = {
  ['useable'] = false,
  ['name'] = 'actionfigure',
  ['image'] = 'actionfigure.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'A small figurine filled which something could be stored inside...',
  ['label'] = 'Action Figure',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['boxmeth'] = {
  ['useable'] = false,
  ['name'] = 'boxmeth',
  ['image'] = 'boxmeth.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Chemical Substance',
  ['label'] = 'Box of Meth',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
['bagmeth'] = {
  ['useable'] = false,
  ['name'] = 'bagmeth',
  ['image'] = 'bagmeth.png',
  ['unique'] = false,
  ['type'] = 'item',
  ['description'] = 'Chemical Substance',
  ['label'] = 'Bag of Meth',
  ['shouldClose'] = false,
  ['weight'] = 100,

},
